apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: openyurt-e2e-test
nodes:
  - role: control-plane
    image: |fill image here|
    extraMounts:
    - hostPath: |fill local bin dir|
      containerPath: /root/openyurt
  - role: worker
    image: |fill image here|